# Generated by Django 3.2.12 on 2022-04-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lenguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Introduzca el idioma en el que está escrito el libro (Castellano, Inglés, Portugués...)', max_length=150)),
            ],
        ),
    ]
